apiVersion: apps/v1  # Specifies Kubernetes API version
kind: Deployment  # Defines the type of resource
metadata:
  name: my-app  # Name of the deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: my-app  # Defines pod labels to match
  template:
    metadata:
      labels:
        app: my-app  # Label to identify pods
    spec:
      containers:
      - name: freddy-repo # Name of the container
        image: 395136124005.dkr.ecr.us-east-1.amazonaws.com/freddy-repo:v1  # Docker image to use
        ports:
        - containerPort: 80  # Exposing ports
