name: ecr
on: 
    workflow_dispatch:
        inputs:
          image_tag:
            type: string
            description: 'Image tag to deploy'
            required: true
            default: 'latest'
    # push:
jobs: 
  ecr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2  
      - name: login into aws ecr 
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
      - name: Build,image to Amazon ECR
        id: build-image
        run: |
         docker build -t freddy-repo:latest .


          
