name: ecr
on: push
jobs: 
  ecr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2  
      -name: login into aws ecr 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
    
 