name : html
on : push
jobs: 
  html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2 

      - name: aws credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
