name: html-and-freddy
on: push
jobs: 
  html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2  

      - name: aws credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
 
      - name: build and deploy
        run: |
         aws s3 sync . s3://fred12334455 

  freddy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2  

      - name: aws credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
 
      - name: build and deploy
        run: |
         aws s3 sync . s3://fred12334455 